//! cudarc-backed GPU paths for `scorer-bntm`, using the streaming
//! cluster store from `scorer-gpu-common`.
//!
//! Compiled only when the `gpu` Cargo feature is enabled. The CUDA
//! kernel source lives in `kernels.cu`; `build.rs` invokes `nvcc` at
//! crate build time to produce `bntm_kernels.ptx` in `OUT_DIR`, which
//! `include_str!` pulls in below. Requires the rapids conda env
//! (provides nvcc 12.4).
//!
//! ## What the GPU path actually does
//!
//! Only the server-side `compute_products` matvec and the
//! `decode_dense_terms` `(AL · g + H · lt_venc)` step move to device.
//! Encryption (`encrypt_cluster`), query encoding (`encode_query`),
//! Protocol 2 verification (`verify_response`), and the host-side
//! composition of the final dense + sparse decode
//! (`decode_scores_with_gpu_dense`) all stay on host.
//!
//! ## Streaming
//!
//! An earlier design held all IVF clusters' device buffers (M_enc, AL,
//! H) device-resident at `upload_cluster` time. Peak VRAM =
//! `n_centroids × m_avg × (n + 2·n_1) × 8` ≈ 50 GB at 8.8 M corpus /
//! 317 centroids on a 32 GB card, which OOMs.
//!
//! Instead, `IvfGpuState` keeps the host-side per-cluster
//! `EncryptedCluster` payload (mmap-backed `m_enc` / `a_l` / `h_mat`)
//! and lazily builds the device-resident `ClusterBuf` on miss. The
//! streaming [`ClusterStore`] holds the device tuple under an LRU
//! bounded by `--gpu-vram-budget-bytes` (default NVML 80 %); on
//! miss-then-evict it drops the LRU tail's `CudaSlice<u64>`s,
//! returning device memory to the cudarc memory pool. A subsequent
//! re-hit re-uploads M_enc + AL + H straight from the host-resident
//! `EncryptedCluster` (materialised once at handle build / cache load;
//! no per-re-hit regeneration).
//!
//! The host-side sparse `S` matrix stays on host in
//! `IvfGpuState::s_mats`; it's never device-resident.
//!
//! Unlike the cuvs scorers (plaintext / sap), BN's cluster device
//! buffers are pure `CudaSlice<u64>` that cudarc owns end-to-end —
//! `Drop` returns memory to the cudarc memory pool cleanly. No
//! manual `cuvsRMMFree` dance, no DLPack deleter suppression. Same
//! streaming shape as EMVP.
//!
//! ## Two variants — flat and IVF
//!
//! - [`FlatGpuState`] backs `BnTmScorer`. Degenerate single-cluster
//!   streaming wrapper; LRU has one entry but the NVML peak sampler
//!   runs uniformly across variants and the surface stays uniform
//!   with `IvfGpuState`.
//! - [`IvfGpuState`] backs `BnTmIvfScorer`. Per-cluster device
//!   buffers uploaded on miss via the same `ClusterStore`, evicted
//!   on budget pressure. Same streaming shape as emvp-IVF GPU.
//!
//! ## Launch-overhead caveat
//!
//! At SEC128 the kernel is small: m × 1024 field ops per cluster,
//! microseconds of compute on V100. The transfer stack (H2D `v_enc`,
//! kernel launch, D2H `r`) dominates per-query latency at our
//! typical cluster size (~316 vectors at 100k corpus / 317 centroids).
//! Future polish: pinned-memory transfers, kernel-fused multi-cluster
//! dispatch, GPU-side decode and verification.

use std::sync::Arc;

use cudarc::driver::{
    CudaContext, CudaFunction, CudaSlice, CudaStream, LaunchConfig, PushKernelArg,
};
use cudarc::nvrtc::Ptx;
use scorer_gpu_common::{
    ClusterStore, ClusterStoreError, DeviceCluster, PeakVramSampler, nvml_index_for_cuda_device,
    resolve_budget,
};

use crate::crypto::SparseMatrix;
use crate::params::BnTmParams;

/// Compiled PTX for the BN kernel. Generated by `build.rs` from
/// `src/gpu/kernels.cu`; the CUDA driver JIT-compiles it at first
/// launch. PTX targets compute_70 → forward-compatible across V100,
/// RTX 5000 Ada, and H100.
const BNTM_KERNEL_PTX: &str = include_str!(concat!(env!("OUT_DIR"), "/bntm_kernels.ptx"));

const KERNEL_COMPUTE_PRODUCTS: &str = "bntm_compute_products";
const KERNEL_DECODE_DENSE: &str = "bntm_decode_dense";
const KERNEL_ADD_MOD_VEC: &str = "bntm_add_mod_vec";

/// One thread per output row; 256 threads per block keeps register
/// pressure modest given the u128 accumulator.
const BLOCK_DIM: u32 = 256;

/// Block size for the elementwise `bntm_add_mod_vec` compose kernel.
/// One thread per output element; no reduction.
const ADD_MOD_BLOCK_DIM: u32 = 256;

#[derive(Debug, thiserror::Error)]
pub enum GpuError {
    #[error("CUDA driver error: {0}")]
    Driver(String),
    #[error("VRAM budget resolution failed: {0}")]
    Budget(String),
    #[error("NVML peak-VRAM sampler failed: {0}")]
    Sampler(String),
    #[error("cluster payload {requested_bytes} bytes exceeds budget {budget_bytes} bytes")]
    BudgetTooSmall {
        budget_bytes: u64,
        requested_bytes: u64,
    },
}

impl From<cudarc::driver::DriverError> for GpuError {
    fn from(e: cudarc::driver::DriverError) -> Self {
        GpuError::Driver(format!("{e:?}"))
    }
}

impl From<scorer_gpu_common::BudgetResolverError> for GpuError {
    fn from(e: scorer_gpu_common::BudgetResolverError) -> Self {
        GpuError::Budget(format!("{e}"))
    }
}

impl From<scorer_gpu_common::SamplerError> for GpuError {
    fn from(e: scorer_gpu_common::SamplerError) -> Self {
        GpuError::Sampler(format!("{e}"))
    }
}

impl From<ClusterStoreError<cudarc::driver::DriverError>> for GpuError {
    fn from(e: ClusterStoreError<cudarc::driver::DriverError>) -> Self {
        match e {
            ClusterStoreError::Upload(c) => GpuError::Driver(format!("{c:?}")),
            ClusterStoreError::BudgetTooSmall {
                budget_bytes,
                requested_bytes,
            } => GpuError::BudgetTooSmall {
                budget_bytes,
                requested_bytes,
            },
            ClusterStoreError::Sync(c) => GpuError::Driver(format!("{c:?}")),
        }
    }
}

/// Process-wide cached CUDA context + loaded BN kernel. Loaded once
/// per process the first time any GPU BN handle is built; shared by
/// every `FlatGpuState` / `IvfGpuState` so we don't re-compile PTX or
/// pay context-creation overhead per cluster. Mirrors the emvp-GPU
/// kernel cache; the two crates each have their own `OnceLock` since
/// they ship different PTX.
struct BnTmKernel {
    /// Drop order matters — keep the context alive for the
    /// OnceLock's `'static` lifetime so the stream / module / function
    /// handles below stay valid.
    #[allow(dead_code)]
    ctx: Arc<CudaContext>,
    stream: Arc<CudaStream>,
    /// Server-side `M_enc · v_enc` matvec at N = 1024.
    compute_products: CudaFunction,
    /// Dense matvec at the n_1 = 512 inner dimension. Launched twice
    /// per decode (for `AL · G` and `H · (L⊤ · v_enc)`).
    decode_dense: CudaFunction,
    /// Elementwise add over F_p, composes the two `decode_dense`
    /// outputs into a single length-`m` dense partial.
    add_mod_vec: CudaFunction,
}

fn kernel() -> Result<&'static BnTmKernel, GpuError> {
    use std::sync::OnceLock;
    static KERNEL: OnceLock<Result<BnTmKernel, String>> = OnceLock::new();

    let res = KERNEL.get_or_init(|| {
        let ctx = CudaContext::new(0).map_err(|e| format!("CudaContext::new: {e:?}"))?;
        let stream = ctx.default_stream();
        let module = ctx
            .load_module(Ptx::from_src(BNTM_KERNEL_PTX))
            .map_err(|e| format!("load_module: {e:?}"))?;
        let load = |name: &str| {
            module
                .load_function(name)
                .map_err(|e| format!("load_function {name}: {e:?}"))
        };
        let compute_products = load(KERNEL_COMPUTE_PRODUCTS)?;
        let decode_dense = load(KERNEL_DECODE_DENSE)?;
        let add_mod_vec = load(KERNEL_ADD_MOD_VEC)?;
        Ok(BnTmKernel {
            ctx,
            stream,
            compute_products,
            decode_dense,
            add_mod_vec,
        })
    });

    match res {
        Ok(k) => Ok(k),
        Err(e) => Err(GpuError::Driver(e.clone())),
    }
}

/// Device-resident per-cluster buffers + the row count they span.
/// Implements [`DeviceCluster`] so the streaming `ClusterStore` can
/// hold it and account its size against the VRAM budget. cudarc owns
/// the three `CudaSlice<u64>`s; `Drop` returns
/// the device memory to the cudarc memory pool — no manual free
/// needed.
///
/// `a_l_dev` and `h_dev` are row-major `m × n_1` and mirror the
/// `m_enc_dev` packing (flat `&[u64]` via `clone_htod`). All three
/// are read by `launch_compute_products` (M_enc) and
/// `launch_decode_dense_terms` (AL, H).
struct ClusterBuf {
    m_enc_dev: CudaSlice<u64>,
    a_l_dev: CudaSlice<u64>,
    h_dev: CudaSlice<u64>,
    m: usize,
}

// SAFETY: cudarc's `CudaSlice<u64>` isn't declared `Sync` upstream
// because the underlying device pointer is a raw FFI handle. The
// `ClusterStore` wraps each `ClusterBuf` in a `Mutex` and only
// reaches it through the `tokio::task::spawn_blocking` worker pool.
// Drop this `unsafe` if cudarc ever exposes `Send`/`Sync` directly
// on `CudaSlice`.
unsafe impl Send for ClusterBuf {}

impl DeviceCluster for ClusterBuf {
    fn device_bytes(&self) -> u64 {
        // M_enc (m·n·8) + AL (m·n_1·8) + H (m·n_1·8). The three
        // slices' `len()`s sum to the field-element count; multiply
        // by 8 for bytes. cudarc's internal scratch / kernel-arg
        // buffers aren't tracked here; the NVML peak sampler is the
        // source of truth for realised VRAM.
        ((self.m_enc_dev.len() + self.a_l_dev.len() + self.h_dev.len()) as u64) * 8
    }
}

/// Upload the three cluster buffers (M_enc + AL + H) to device via
/// the supplied stream. Used inside the `ClusterStore::get_or_upload`
/// closure; the stream is the store's dedicated upload stream so
/// these copies overlap compute on the sibling compute stream.
fn upload_cluster_buffers(
    stream: &Arc<CudaStream>,
    m_enc_host: &[u64],
    a_l_host: &[u64],
    h_host: &[u64],
    m: usize,
    params: BnTmParams,
) -> Result<ClusterBuf, cudarc::driver::DriverError> {
    debug_assert_eq!(m_enc_host.len(), m * params.n());
    debug_assert_eq!(a_l_host.len(), m * params.n1());
    debug_assert_eq!(h_host.len(), m * params.n1());
    let m_enc_dev = stream.clone_htod(m_enc_host)?;
    let a_l_dev = stream.clone_htod(a_l_host)?;
    let h_dev = stream.clone_htod(h_host)?;
    Ok(ClusterBuf {
        m_enc_dev,
        a_l_dev,
        h_dev,
        m,
    })
}

// ---------------------------------------------------------------------------
// Flat variant
// ---------------------------------------------------------------------------

/// Flat GPU state for `BnTmScorer`. Single-cluster streaming wrapper.
/// The LRU is degenerate (one cluster) but the surface stays uniform
/// with `IvfGpuState` and the NVML peak sampler runs uniformly across
/// variants.
///
/// Host-side M_enc / AL / H stay around so the upload closure can
/// rebuild on (degenerate) LRU eviction and so the NVML sampler can
/// run over the whole handle lifetime. The sparse `S` matrix is held
/// here and shared with the host-side decode orchestrator via
/// [`s_mat_arc`](Self::s_mat_arc).
pub struct FlatGpuState {
    m_enc_host: Vec<u64>,
    a_l_host: Vec<u64>,
    h_host: Vec<u64>,
    m: usize,
    params: BnTmParams,
    store: ClusterStore<ClusterBuf>,
    sampler: Option<PeakVramSampler>,
    /// Pre-derived sparse `S` matrix, shared with the host-side decode
    /// orchestrator. Memory ≈ `m · μn · 5 B` at SEC128 (≈ 18 MiB at
    /// m = 100 000).
    s_mat: Arc<SparseMatrix>,
}

impl FlatGpuState {
    /// Construct the streaming state. The device cluster buffer
    /// isn't built yet — the first `compute_products` (or
    /// `decode_dense_terms`) call triggers the upload via
    /// `ClusterStore::get_or_upload`. Matches the IVF variant's
    /// lazy-upload semantics so the NVML sampler runs from
    /// handle-build through the first kernel launch.
    pub fn build(
        m_enc_host: &[u64],
        a_l_host: &[u64],
        h_host: &[u64],
        s_mat: Arc<SparseMatrix>,
        m: usize,
        params: BnTmParams,
        vram_budget_bytes: Option<u64>,
    ) -> Result<Self, GpuError> {
        let k = kernel()?;
        let upload_stream = k.ctx.new_stream()?;
        let compute_stream = k.ctx.new_stream()?;
        let nvml_idx = nvml_index_for_cuda_device(0);
        let budget = resolve_budget(vram_budget_bytes, nvml_idx)?;
        let store = ClusterStore::<ClusterBuf>::new(
            Arc::clone(&k.ctx),
            budget,
            upload_stream,
            compute_stream,
        );
        let sampler = PeakVramSampler::start_default(nvml_idx).ok();

        Ok(FlatGpuState {
            m_enc_host: m_enc_host.to_vec(),
            a_l_host: a_l_host.to_vec(),
            h_host: h_host.to_vec(),
            m,
            params,
            store,
            sampler,
            s_mat,
        })
    }

    pub fn peak_vram_bytes(&self) -> Option<u64> {
        self.sampler.as_ref().map(|s| s.peak_bytes())
    }

    pub fn vram_budget_bytes(&self) -> u64 {
        self.store.budget_bytes()
    }

    /// `Arc` clone of the cached sparse `S` so the caller can move it
    /// into a `spawn_blocking` closure ahead of the
    /// `decode_scores_with_gpu_dense` call.
    pub fn s_mat_arc(&self) -> Arc<SparseMatrix> {
        Arc::clone(&self.s_mat)
    }

    /// Compute the per-query device payload size hint that the
    /// streaming store uses to pre-evict on alloc-fail. Matches
    /// `ClusterBuf::device_bytes` for the flat handle.
    fn payload_hint(&self) -> u64 {
        (self.m as u64) * (self.params.n() as u64 + 2 * (self.params.n1() as u64)) * 8
    }

    /// Run `compute_products` for one query against the device-
    /// resident cluster (uploaded lazily on first call). `v_enc` is
    /// the host-side encoded query (already padded to n by
    /// `crypto::encode_query`); returns the length-m response vector
    /// r in F_p, identical to the CPU `crypto::compute_products`
    /// output.
    pub fn compute_products(&self, v_enc: &[u64]) -> Result<Vec<u64>, GpuError> {
        debug_assert_eq!(v_enc.len(), self.params.n());
        let k = kernel()?;
        let m = self.m;
        let params = self.params;
        let m_enc_host = &self.m_enc_host;
        let a_l_host = &self.a_l_host;
        let h_host = &self.h_host;
        let cell = self.store.get_or_upload::<_, cudarc::driver::DriverError>(
            0,
            self.payload_hint(),
            |upload_stream| {
                upload_cluster_buffers(upload_stream, m_enc_host, a_l_host, h_host, m, params)
            },
        )?;
        let cluster = cell.lock();
        launch_compute_products(k, &cluster, v_enc)
    }

    /// Compute the dense partial of the decode-side correction:
    /// `AL · g + H · lt_venc` over F_p, returned as a length-`m` host
    /// vector.
    ///
    /// Two H2D copies per query (`g` and `lt_venc`, each length n_1),
    /// two `bntm_decode_dense` launches against the device-resident
    /// `AL` and `H`, one `bntm_add_mod_vec` to combine the outputs,
    /// one D2H. The sparse pieces (`M · T`, `S · v_enc`) stay on
    /// host and are subtracted by `decode_scores_with_gpu_dense`.
    pub fn decode_dense_terms(&self, g: &[u64], lt_venc: &[u64]) -> Result<Vec<u64>, GpuError> {
        debug_assert_eq!(g.len(), self.params.n1());
        debug_assert_eq!(lt_venc.len(), self.params.n1());
        let k = kernel()?;
        let m = self.m;
        let params = self.params;
        let m_enc_host = &self.m_enc_host;
        let a_l_host = &self.a_l_host;
        let h_host = &self.h_host;
        let cell = self.store.get_or_upload::<_, cudarc::driver::DriverError>(
            0,
            self.payload_hint(),
            |upload_stream| {
                upload_cluster_buffers(upload_stream, m_enc_host, a_l_host, h_host, m, params)
            },
        )?;
        let cluster = cell.lock();
        launch_decode_dense_terms(k, &cluster, g, lt_venc)
    }
}

// ---------------------------------------------------------------------------
// IVF variant — streaming. Host-side per-cluster EncryptedCluster
// payloads (mmap-backed `m_enc` / `a_l`) uploaded lazily on miss; H
// regenerated from each cluster's `h_seed` in the upload closure; LRU
// evicts on budget pressure. The sparse `S` matrix per cluster is held
// host-side in `s_mats`, never device-resident.
// ---------------------------------------------------------------------------

/// Streaming GPU state for `BnTmIvfScorer`. Shares the scorer's
/// `Arc<Vec<EncryptedCluster>>` so the upload closure can read each
/// cluster's `m_enc` / `a_l` directly — which is **zero-copy** when
/// the cache file is mmap-backed (the 8.8M build path at scale).
pub struct IvfGpuState {
    clusters: Arc<Vec<crate::EncryptedCluster>>,
    /// Pre-derived sparse `S` matrices, one per cluster (or `None` for
    /// empty clusters). Eagerly generated at `build()` time so the GPU
    /// decode dispatch can compute `S · v_enc` per query on host
    /// without re-running the single-threaded ChaCha20 sample loop.
    /// Host RAM cost ≈
    /// `n_centroids · m_avg · μn · 5 B` (≈ 5 GB at 8.8 M / 317
    /// centroids, well within the sacs006 RAM budget).
    s_mats: Vec<Option<Arc<SparseMatrix>>>,
    params: BnTmParams,
    store: ClusterStore<ClusterBuf>,
    sampler: Option<PeakVramSampler>,
}

impl IvfGpuState {
    /// Build the streaming state from the scorer's per-cluster
    /// encrypted state. We hold an `Arc<Vec<EncryptedCluster>>`
    /// directly so mmap-backed `m_enc` / `a_l` regions stay
    /// page-cache-zero-copy through the streaming upload path.
    pub fn build(
        clusters: Arc<Vec<crate::EncryptedCluster>>,
        params: BnTmParams,
        vram_budget_bytes: Option<u64>,
    ) -> Result<Self, GpuError> {
        let k = kernel()?;
        let upload_stream = k.ctx.new_stream()?;
        let compute_stream = k.ctx.new_stream()?;
        let nvml_idx = nvml_index_for_cuda_device(0);
        let budget = resolve_budget(vram_budget_bytes, nvml_idx)?;
        let store = ClusterStore::<ClusterBuf>::new(
            Arc::clone(&k.ctx),
            budget,
            upload_stream,
            compute_stream,
        );
        let sampler = PeakVramSampler::start_default(nvml_idx).ok();

        // S is already materialised on each `EncryptedCluster` (Plan
        // 28) — just Arc-clone it, no regeneration needed.
        let s_mats: Vec<Option<Arc<SparseMatrix>>> = clusters
            .iter()
            .map(|c| {
                if c.m == 0 {
                    None
                } else {
                    Some(Arc::clone(&c.s_mat))
                }
            })
            .collect();

        Ok(IvfGpuState {
            clusters,
            s_mats,
            params,
            store,
            sampler,
        })
    }

    pub fn peak_vram_bytes(&self) -> Option<u64> {
        self.sampler.as_ref().map(|s| s.peak_bytes())
    }

    pub fn vram_budget_bytes(&self) -> u64 {
        self.store.budget_bytes()
    }

    /// `Arc` clone of one cluster's cached sparse `S`. `None` for
    /// empty / out-of-range clusters; otherwise the caller moves the
    /// Arc into a `spawn_blocking` closure ahead of the
    /// `decode_scores_with_gpu_dense` call.
    pub fn s_mat_arc(&self, ci: usize) -> Option<Arc<SparseMatrix>> {
        self.s_mats.get(ci).and_then(|s| s.clone())
    }

    fn cluster_payload_hint(&self, m: usize) -> u64 {
        (m as u64) * (self.params.n() as u64 + 2 * (self.params.n1() as u64)) * 8
    }

    /// Run `compute_products` for cluster `ci`, uploading on miss +
    /// evicting LRU tail under budget pressure. Returns `None` for
    /// empty / out-of-range clusters so the caller can skip them.
    pub fn compute_products(&self, ci: usize, v_enc: &[u64]) -> Result<Option<Vec<u64>>, GpuError> {
        debug_assert_eq!(v_enc.len(), self.params.n());
        let Some(cluster_meta) = self.clusters.get(ci) else {
            return Ok(None);
        };
        let m = cluster_meta.m;
        if m == 0 {
            return Ok(None);
        }
        let k = kernel()?;
        let params = self.params;
        let clusters = Arc::clone(&self.clusters);
        let cell = self.store.get_or_upload::<_, cudarc::driver::DriverError>(
            ci,
            self.cluster_payload_hint(m),
            move |upload_stream| {
                let c = &clusters[ci];
                upload_cluster_buffers(
                    upload_stream,
                    c.m_enc.as_slice(),
                    c.a_l.as_slice(),
                    c.h_mat.as_slice(),
                    m,
                    params,
                )
            },
        )?;
        let cluster = cell.lock();
        let r = launch_compute_products(k, &cluster, v_enc)?;
        Ok(Some(r))
    }

    /// `AL · g + H · lt_venc` for one cluster. Mirrors
    /// [`FlatGpuState::decode_dense_terms`]; `None` for empty /
    /// out-of-range clusters.
    pub fn decode_dense_terms(
        &self,
        ci: usize,
        g: &[u64],
        lt_venc: &[u64],
    ) -> Result<Option<Vec<u64>>, GpuError> {
        debug_assert_eq!(g.len(), self.params.n1());
        debug_assert_eq!(lt_venc.len(), self.params.n1());
        let Some(cluster_meta) = self.clusters.get(ci) else {
            return Ok(None);
        };
        let m = cluster_meta.m;
        if m == 0 {
            return Ok(None);
        }
        let k = kernel()?;
        let params = self.params;
        let clusters = Arc::clone(&self.clusters);
        let cell = self.store.get_or_upload::<_, cudarc::driver::DriverError>(
            ci,
            self.cluster_payload_hint(m),
            move |upload_stream| {
                let c = &clusters[ci];
                upload_cluster_buffers(
                    upload_stream,
                    c.m_enc.as_slice(),
                    c.a_l.as_slice(),
                    c.h_mat.as_slice(),
                    m,
                    params,
                )
            },
        )?;
        let cluster = cell.lock();
        let r = launch_decode_dense_terms(k, &cluster, g, lt_venc)?;
        Ok(Some(r))
    }
}

// ---------------------------------------------------------------------------
// Kernel launch glue.
// ---------------------------------------------------------------------------

fn launch_compute_products(
    k: &BnTmKernel,
    cluster: &ClusterBuf,
    v_enc: &[u64],
) -> Result<Vec<u64>, GpuError> {
    let m = cluster.m;
    let v_dev = k.stream.clone_htod(v_enc)?;
    let mut r_dev: CudaSlice<u64> = k.stream.alloc_zeros(m)?;

    let m_u32 = u32::try_from(m).expect("cluster size must fit in u32");
    // Warp-per-row layout. One block per output row, 256 threads per
    // block cooperatively reducing the N=1024 dot product. Shared
    // memory holds v_enc (1024 × 8 = 8192 bytes) and 8 cross-warp
    // partials (overlapped into the same 8192-byte declaration on the
    // kernel side; we pass the v_enc cache size here).
    let cfg = LaunchConfig {
        grid_dim: (m_u32, 1, 1),
        block_dim: (BLOCK_DIM, 1, 1),
        shared_mem_bytes: 0,
    };

    let mut launch = k.stream.launch_builder(&k.compute_products);
    launch.arg(&cluster.m_enc_dev);
    launch.arg(&v_dev);
    launch.arg(&mut r_dev);
    launch.arg(&m_u32);
    unsafe { launch.launch(cfg)? };

    let r = k.stream.clone_dtoh(&r_dev)?;
    Ok(r)
}

/// Compose `AL · g + H · lt_venc` on device and return the length-`m`
/// result as a host vector.
///
/// One `bntm_decode_dense` launch per matrix (the kernel reads any
/// `m × n_1` row-major buffer in F_p), then one `bntm_add_mod_vec`
/// over the two length-`m` outputs. `g` and `lt_venc` are uploaded
/// with two separate H2Ds per query.
fn launch_decode_dense_terms(
    k: &BnTmKernel,
    cluster: &ClusterBuf,
    g: &[u64],
    lt_venc: &[u64],
) -> Result<Vec<u64>, GpuError> {
    let m = cluster.m;
    let m_u32 = u32::try_from(m).expect("cluster size must fit in u32");

    let g_dev = k.stream.clone_htod(g)?;
    let lt_venc_dev = k.stream.clone_htod(lt_venc)?;

    let dense_cfg = LaunchConfig {
        grid_dim: (m_u32, 1, 1),
        block_dim: (BLOCK_DIM, 1, 1),
        shared_mem_bytes: 0,
    };

    // r1 = AL · g
    let mut r1_dev: CudaSlice<u64> = k.stream.alloc_zeros(m)?;
    let mut launch = k.stream.launch_builder(&k.decode_dense);
    launch.arg(&cluster.a_l_dev);
    launch.arg(&g_dev);
    launch.arg(&mut r1_dev);
    launch.arg(&m_u32);
    unsafe { launch.launch(dense_cfg)? };

    // r2 = H · lt_venc
    let mut r2_dev: CudaSlice<u64> = k.stream.alloc_zeros(m)?;
    let mut launch = k.stream.launch_builder(&k.decode_dense);
    launch.arg(&cluster.h_dev);
    launch.arg(&lt_venc_dev);
    launch.arg(&mut r2_dev);
    launch.arg(&m_u32);
    unsafe { launch.launch(dense_cfg)? };

    // out = r1 + r2  (mod P)
    let mut out_dev: CudaSlice<u64> = k.stream.alloc_zeros(m)?;
    let add_grid = m_u32.div_ceil(ADD_MOD_BLOCK_DIM);
    let add_cfg = LaunchConfig {
        grid_dim: (add_grid, 1, 1),
        block_dim: (ADD_MOD_BLOCK_DIM, 1, 1),
        shared_mem_bytes: 0,
    };
    let mut launch = k.stream.launch_builder(&k.add_mod_vec);
    launch.arg(&r1_dev);
    launch.arg(&r2_dev);
    launch.arg(&mut out_dev);
    launch.arg(&m_u32);
    unsafe { launch.launch(add_cfg)? };

    let out = k.stream.clone_dtoh(&out_dev)?;
    Ok(out)
}
