//! cudarc-backed GPU paths for `scorer-emvp`.
//!
//! Compiled only when the `gpu` Cargo feature is enabled. The CUDA
//! kernel source lives in `kernels.cu`; `build.rs` invokes `nvcc`
//! at crate build time to produce `emvp_kernels.ptx` in `OUT_DIR`,
//! which `include_str!` pulls in below. Building requires nvcc on
//! PATH.
//!
//! ## What the GPU path actually does
//!
//! Only the server-side block-GEMV (`compute_products`) moves to
//! device. Encryption, query encoding (`encode_query`), and decoding
//! (`decode_scores` — the second m × n field-mul pass that subtracts
//! R) all stay on host. Decode is kept on CPU; moving it to GPU is a
//! possible future optimisation.
//!
//! ## Two variants — flat and IVF
//!
//! - [`FlatGpuState`] backs `EmvpScorer` (the flat, single-cluster
//!   variant). One device-resident M̂ buffer, uploaded lazily on
//!   the first `compute_products` call via the streaming
//!   [`ClusterStore`]. Each `score()` call uploads q̂, launches the
//!   kernel, downloads the s × m partials.
//! - [`IvfGpuState`] backs `EmvpIvfScorer`. Per-cluster device M̂
//!   buffers are uploaded on miss via the same `ClusterStore`,
//!   evicted on budget pressure. Routing on host (cleartext
//!   centroids — EMVP is not distance-preserving so the server
//!   can't route); per-probed-cluster kernel launch; partials
//!   accumulated and decoded on host. Same streaming shape as the
//!   plaintext / sap-IVF GPU paths.
//!
//! ## Streaming
//!
//! Unlike the cuvs scorers (plaintext / sap), EMVP's cluster device
//! payload is a `CudaSlice<u64>` that cudarc owns end-to-end:
//! `Drop` returns memory to the cudarc memory pool cleanly. No
//! manual `cuvsRMMFree` dance, no DLPack deleter suppression. The
//! streaming pattern is therefore strictly an LRU bookkeeping +
//! NVML-sampled peak-VRAM accounting on top of the existing
//! per-cluster `ClusterBuf`.
//!
//! ## Launch-overhead caveat
//!
//! At SEC128 the kernel is small: ~m × 1292 field ops per cluster,
//! microseconds of compute on a V100. The transfer stack (H2D q̂ copy,
//! kernel launch, D2H partials copy) will dominate per-query latency
//! at our typical cluster size (~316 vectors at 100k corpus / 317
//! centroids); benchmarks should report this honestly. Future polish:
//! pinned-memory transfers, kernel-fused multi-cluster dispatch,
//! GPU-side decode.

use std::sync::Arc;

use cudarc::driver::{
    CudaContext, CudaFunction, CudaSlice, CudaStream, LaunchConfig, PushKernelArg,
};
use cudarc::nvrtc::Ptx;
use scorer_gpu_common::{
    ClusterStore, ClusterStoreError, DeviceCluster, PeakVramSampler, nvml_index_for_cuda_device,
    resolve_budget,
};

use crate::params::SEC128;

/// Compiled PTX for the EMVP kernel. Generated by `build.rs` from
/// `src/gpu/kernels.cu`; the CUDA driver JIT-compiles it to whatever
/// SM the host GPU has at first launch (PTX targets compute_70 →
/// works on V100 / RTX 5000 Ada / H100 unchanged).
const EMVP_KERNEL_PTX: &str = include_str!(concat!(env!("OUT_DIR"), "/emvp_kernels.ptx"));

const KERNEL_NAME: &str = "emvp_compute_products";

/// 16×16 thread block — matches the kernel doc's grid layout.
/// Per-output-cell threads, so `block_dim.x` walks the row index `i`
/// and `block_dim.y` walks the block index `si`.
const BLOCK_DIM_X: u32 = 16;
const BLOCK_DIM_Y: u32 = 16;

#[derive(Debug, thiserror::Error)]
pub enum GpuError {
    #[error("CUDA driver error: {0}")]
    Driver(String),
    #[error("VRAM budget resolution failed: {0}")]
    Budget(String),
    #[error("NVML peak-VRAM sampler failed: {0}")]
    Sampler(String),
    #[error("cluster payload {requested_bytes} bytes exceeds budget {budget_bytes} bytes")]
    BudgetTooSmall {
        budget_bytes: u64,
        requested_bytes: u64,
    },
}

impl From<cudarc::driver::DriverError> for GpuError {
    fn from(e: cudarc::driver::DriverError) -> Self {
        GpuError::Driver(format!("{e:?}"))
    }
}

impl From<scorer_gpu_common::BudgetResolverError> for GpuError {
    fn from(e: scorer_gpu_common::BudgetResolverError) -> Self {
        GpuError::Budget(format!("{e}"))
    }
}

impl From<scorer_gpu_common::SamplerError> for GpuError {
    fn from(e: scorer_gpu_common::SamplerError) -> Self {
        GpuError::Sampler(format!("{e}"))
    }
}

impl From<ClusterStoreError<cudarc::driver::DriverError>> for GpuError {
    fn from(e: ClusterStoreError<cudarc::driver::DriverError>) -> Self {
        match e {
            ClusterStoreError::Upload(c) => GpuError::Driver(format!("{c:?}")),
            ClusterStoreError::BudgetTooSmall {
                budget_bytes,
                requested_bytes,
            } => GpuError::BudgetTooSmall {
                budget_bytes,
                requested_bytes,
            },
            ClusterStoreError::Sync(c) => GpuError::Driver(format!("{c:?}")),
        }
    }
}

/// Process-wide cached CUDA context + loaded EMVP kernel. Loaded once
/// per process the first time any GPU EMVP handle is built; shared by
/// every `FlatGpuState` / `IvfGpuState` so we don't re-compile PTX or
/// pay context-creation overhead per cluster.
struct EmvpKernel {
    /// The context owns the stream and module lifetimes; it's not
    /// referenced after construction but dropping it would invalidate
    /// the stream / module / function handles below. Keep it alive
    /// for the OnceLock's `'static` lifetime.
    #[allow(dead_code)]
    ctx: Arc<CudaContext>,
    stream: Arc<CudaStream>,
    func: CudaFunction,
}

fn kernel() -> Result<&'static EmvpKernel, GpuError> {
    use std::sync::OnceLock;
    static KERNEL: OnceLock<Result<EmvpKernel, String>> = OnceLock::new();

    // Instantiate the kernel lazily. `Result<_, String>` rather than
    // `Result<_, GpuError>` because `OnceLock`'s value must be `'static`
    // and `DriverError` is not. We re-wrap as `GpuError` on the way
    // out.
    let res = KERNEL.get_or_init(|| {
        let ctx = CudaContext::new(0).map_err(|e| format!("CudaContext::new: {e:?}"))?;
        let stream = ctx.default_stream();
        let module = ctx
            .load_module(Ptx::from_src(EMVP_KERNEL_PTX))
            .map_err(|e| format!("load_module: {e:?}"))?;
        let func = module
            .load_function(KERNEL_NAME)
            .map_err(|e| format!("load_function {KERNEL_NAME}: {e:?}"))?;
        Ok(EmvpKernel { ctx, stream, func })
    });

    match res {
        Ok(k) => Ok(k),
        Err(e) => Err(GpuError::Driver(e.clone())),
    }
}

/// One device-resident M̂ buffer + the row count it spans.
/// Implements [`DeviceCluster`] so the streaming `ClusterStore` can
/// hold it and account its size against the VRAM budget. cudarc
/// owns the `CudaSlice<u64>`; `Drop` returns the device memory to
/// the cudarc memory pool — no manual free needed (unlike the cuVS
/// path in plaintext / sap, where `cuvsRMMFree` had to land on the
/// dataset device pointer manually).
struct ClusterBuf {
    m_hat_dev: CudaSlice<u64>,
    m: usize,
}

// SAFETY: cudarc's `CudaSlice<u64>` isn't declared `Sync` upstream
// because its underlying device pointer is a raw FFI handle. The
// `ClusterStore` wraps each `ClusterBuf` in a `Mutex` and only
// reaches it through the `tokio::task::spawn_blocking` worker pool.
// Drop this `unsafe` if cudarc ever exposes `Send`/`Sync` directly
// on `CudaSlice`.
unsafe impl Send for ClusterBuf {}

impl DeviceCluster for ClusterBuf {
    fn device_bytes(&self) -> u64 {
        // M̂ residency: m × n × 8 (n = SEC128.n = 1292). Internal
        // cudarc memory-pool scratch / kernel-arg buffers aren't
        // tracked here; the NVML peak sampler is the source of
        // truth for realised VRAM.
        (self.m as u64) * (SEC128.n as u64) * 8
    }
}

fn upload_m_hat(
    stream: &Arc<CudaStream>,
    m_hat_host: &[u64],
    m: usize,
) -> Result<ClusterBuf, cudarc::driver::DriverError> {
    debug_assert_eq!(m_hat_host.len(), m * SEC128.n);
    let m_hat_dev = stream.clone_htod(m_hat_host)?;
    Ok(ClusterBuf { m_hat_dev, m })
}

// ---------------------------------------------------------------------------
// Flat variant
// ---------------------------------------------------------------------------

/// Flat GPU state for `EmvpScorer`. Single-cluster streaming
/// wrapper. The LRU is degenerate (one cluster) but the surface
/// stays uniform with `IvfGpuState` and the NVML peak sampler runs
/// uniformly across variants.
pub struct FlatGpuState {
    /// Host-side encrypted M̂ kept around so the upload closure can
    /// rebuild on (degenerate) LRU eviction and so the NVML sampler
    /// can run over the whole handle lifetime.
    m_hat_host: Vec<u64>,
    m: usize,
    store: ClusterStore<ClusterBuf>,
    sampler: Option<PeakVramSampler>,
}

impl FlatGpuState {
    /// Construct the streaming state. The M̂ device buffer isn't
    /// built yet — the first `compute_products` call triggers the
    /// upload via `ClusterStore::get_or_upload`. Matches the IVF
    /// variant's lazy-upload semantics so the sampler runs from
    /// handle-build through the first kernel launch.
    pub fn build(
        m_hat_host: &[u64],
        m: usize,
        vram_budget_bytes: Option<u64>,
    ) -> Result<Self, GpuError> {
        let k = kernel()?;
        let upload_stream = k.ctx.new_stream()?;
        let compute_stream = k.ctx.new_stream()?;
        let nvml_idx = nvml_index_for_cuda_device(0);
        let budget = resolve_budget(vram_budget_bytes, nvml_idx)?;
        let store = ClusterStore::<ClusterBuf>::new(
            Arc::clone(&k.ctx),
            budget,
            upload_stream,
            compute_stream,
        );
        let sampler = PeakVramSampler::start_default(nvml_idx).ok();

        Ok(FlatGpuState {
            m_hat_host: m_hat_host.to_vec(),
            m,
            store,
            sampler,
        })
    }

    pub fn peak_vram_bytes(&self) -> Option<u64> {
        self.sampler.as_ref().map(|s| s.peak_bytes())
    }

    pub fn vram_budget_bytes(&self) -> u64 {
        self.store.budget_bytes()
    }

    /// Run `compute_products` for one query against the
    /// device-resident matrix (uploaded lazily on first call).
    /// `q_hat` is a host-side n-element vector already encoded by
    /// the caller via `crypto::encode_query`; returns the s × m
    /// partials in block-major order, identical layout to the CPU
    /// `crypto::compute_products`.
    pub fn compute_products(&self, q_hat: &[u64]) -> Result<Vec<u64>, GpuError> {
        debug_assert_eq!(q_hat.len(), SEC128.n);
        let k = kernel()?;

        let m = self.m;
        let m_hat_host = &self.m_hat_host;
        let payload_hint = (m as u64) * (SEC128.n as u64) * 8;
        let cell = self.store.get_or_upload::<_, cudarc::driver::DriverError>(
            0,
            payload_hint,
            |upload_stream| upload_m_hat(upload_stream, m_hat_host, m),
        )?;
        let cluster = cell.lock();
        launch_compute_products(k, &cluster, q_hat)
    }
}

// ---------------------------------------------------------------------------
// IVF variant — streaming. Host-side per-cluster M̂ payloads uploaded
// lazily on miss; LRU evicts on budget pressure. Shares the
// process-wide `EmvpKernel` context + module + function — the
// ClusterStore's upload + compute streams are sibling streams on the
// same `Arc<CudaContext>`, so cluster device buffers are visible to
// kernel launches without cross-context plumbing.
// ---------------------------------------------------------------------------

/// Streaming GPU state for `EmvpIvfScorer`. Shares the scorer's
/// `Arc<Vec<EncryptedCluster>>` so the upload closure can read each
/// cluster's M̂ via `EncryptedCluster::m_hat.as_slice()` — which is
/// **zero-copy** when the cache file is mmap-backed (`Mhat::Mmap`,
/// the multi-million-vector build path). Allocating an intermediate
/// `Arc<[u64]>` per cluster would copy each cluster's payload
/// (m × n × 8 bytes) into the heap, summing to tens of GB at that
/// scale and defeating the whole point of the mmap backing (it would
/// re-introduce the out-of-memory condition the mmap path avoids).
pub struct IvfGpuState {
    clusters: Arc<Vec<crate::EncryptedCluster>>,
    store: ClusterStore<ClusterBuf>,
    sampler: Option<PeakVramSampler>,
}

impl IvfGpuState {
    /// Build the streaming state from the scorer's per-cluster
    /// encrypted state. We hold an `Arc<Vec<EncryptedCluster>>`
    /// directly so mmap-backed `m_hat` regions stay
    /// page-cache-zero-copy through the streaming upload path.
    pub fn build(
        clusters: Arc<Vec<crate::EncryptedCluster>>,
        vram_budget_bytes: Option<u64>,
    ) -> Result<Self, GpuError> {
        let k = kernel()?;
        let upload_stream = k.ctx.new_stream()?;
        let compute_stream = k.ctx.new_stream()?;
        let nvml_idx = nvml_index_for_cuda_device(0);
        let budget = resolve_budget(vram_budget_bytes, nvml_idx)?;
        let store = ClusterStore::<ClusterBuf>::new(
            Arc::clone(&k.ctx),
            budget,
            upload_stream,
            compute_stream,
        );
        let sampler = PeakVramSampler::start_default(nvml_idx).ok();

        Ok(IvfGpuState {
            clusters,
            store,
            sampler,
        })
    }

    pub fn peak_vram_bytes(&self) -> Option<u64> {
        self.sampler.as_ref().map(|s| s.peak_bytes())
    }

    pub fn vram_budget_bytes(&self) -> u64 {
        self.store.budget_bytes()
    }

    /// Run `compute_products` for one query against cluster `ci`'s
    /// device-resident matrix, uploading on miss + evicting LRU
    /// tail under budget pressure. Returns `None` for empty /
    /// out-of-range clusters so the caller can skip them.
    pub fn compute_products(&self, ci: usize, q_hat: &[u64]) -> Result<Option<Vec<u64>>, GpuError> {
        debug_assert_eq!(q_hat.len(), SEC128.n);
        let Some(cluster) = self.clusters.get(ci) else {
            return Ok(None);
        };
        let m = cluster.m;
        if m == 0 {
            return Ok(None);
        }
        let k = kernel()?;
        let clusters = Arc::clone(&self.clusters);
        let payload_hint = (m as u64) * (SEC128.n as u64) * 8;
        let cell = self.store.get_or_upload::<_, cudarc::driver::DriverError>(
            ci,
            payload_hint,
            move |upload_stream| upload_m_hat(upload_stream, clusters[ci].m_hat.as_slice(), m),
        )?;
        let cluster = cell.lock();
        let partials = launch_compute_products(k, &cluster, q_hat)?;
        Ok(Some(partials))
    }
}

// ---------------------------------------------------------------------------
// Kernel launch glue — shared by flat and IVF.
// ---------------------------------------------------------------------------

fn launch_compute_products(
    k: &EmvpKernel,
    cluster: &ClusterBuf,
    q_hat: &[u64],
) -> Result<Vec<u64>, GpuError> {
    let m = cluster.m;
    let s_blocks = SEC128.s;

    // H2D: query (n u64 = 10 KB at SEC128). Allocate the partials
    // buffer up front so the kernel's output write has a target.
    let q_dev = k.stream.clone_htod(q_hat)?;
    let mut partials_dev: CudaSlice<u64> = k.stream.alloc_zeros(s_blocks * m)?;

    let m_u32 = u32::try_from(m).expect("cluster size must fit in u32");
    let cfg = LaunchConfig {
        grid_dim: (
            m_u32.div_ceil(BLOCK_DIM_X),
            (s_blocks as u32).div_ceil(BLOCK_DIM_Y),
            1,
        ),
        block_dim: (BLOCK_DIM_X, BLOCK_DIM_Y, 1),
        shared_mem_bytes: 0,
    };

    let mut launch = k.stream.launch_builder(&k.func);
    launch.arg(&cluster.m_hat_dev);
    launch.arg(&q_dev);
    launch.arg(&mut partials_dev);
    launch.arg(&m_u32);
    unsafe { launch.launch(cfg)? };

    // D2H: partials (s × m u64). `clone_dtoh` waits for the launch.
    let partials = k.stream.clone_dtoh(&partials_dev)?;
    Ok(partials)
}
